In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# Solution 1

Yes ,both the variables have the different datatypes.

In [6]:
type(list_)

list

In [7]:
type(array_list)

numpy.ndarray

# Solution 2

In [8]:
# Data type of each element in list_
print("Element types in list_:")
for item in list_:
    print(type(item))

# Data type of each element in array_list
print("\nElement types in array_list:")
for item in array_list:
    print(type(item))


Element types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Element types in array_list:
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# Solution 3

In [9]:
array_list = np.array(object=list_, dtype=int)

# Checking element types again
print("Element types in list_:")
for item in list_:
    print(type(item))

print("\nElement types in array_list (after dtype=int):")
for item in array_list:
    print(type(item))


Element types in list_:
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

Element types in array_list (after dtype=int):
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


# Solution 4

In [11]:
num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)


Shape of num_array: (2, 3)
Size of num_array: 6


# Solution 5

In [12]:
zero_matrix = np.zeros((3, 3))
print("3x3 Zero Matrix:\n", zero_matrix)


3x3 Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# Solution 6

In [13]:
identity_matrix = np.identity(5)
print("5x5 Identity Matrix:\n", identity_matrix)


5x5 Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
